version: "3"

services:
  spicedb:
    container_name: "spicedb"
    image: authzed/spicedb:latest
    ports:
      - "50051:50051"
    command: serve --grpc-preshared-key "test_key"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:50051 -Xms256m -Xmx4G"

    networks:
      - pulse8-central-bridge

  pulse8-core-access-control:
    container_name: pulse8-core-access-control
    image: pulse8-core-access-control:latest
    depends_on:
      - spicedb
    ports:
      - "3010:3010"
      - "5010:5010"
    networks:
      - pulse8-central-bridge
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms256m -Xmx4G"
      SPICEDB_HOST: spicedb
      SPICEDB_PORT: 50051
      SPICEDB_PRESHARED_KEY: test_key
  echo-server:
    container_name: "echoserver"
    image: inanimate/echo-server:latest
    ports:
      - "3000:8080"
    networks:
      - pulse8-central-bridge
  kong:
    image: kong/kong-gateway:3.5
    container_name: pulse8-kong
    env_file:
      - docker-compose.env
    environment:
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key
      KONG_CLUSTER_CERT: /certs/cluster.crt
    volumes:
      - ./certs:/certs
    ports:
      - 8000:8000
    networks:
      - pulse8-central-bridge
networks:
  pulse8-central-bridge:
    name: pulse8-central-bridge
