version: "3"

services:
  spicedb:
    container_name: "spicedb"
    image: authzed/spicedb:latest
    ports:
      - "50051:50051"
    command: serve --grpc-preshared-key "test_key"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:50051 -Xms256m -Xmx4G"

    networks:
      - pulse8-central-bridge

  pulse8-core-access-control:
    container_name: pulse8-core-access-control
    image: pulse8-core-access-control:latest
    depends_on:
      - spicedb
    ports:
      - "3010:3010"
      - "5010:5010"
    networks:
      - pulse8-central-bridge
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms256m -Xmx4G"
      SPICEDB_HOST: spicedb
      SPICEDB_PORT: 50051
      SPICEDB_PRESHARED_KEY: test_key
  echo-server:
    container_name: echoserver
    image: inanimate/echo-server:latest
    ports:
      - 3000:8080
  keycloak:
    container_name: pulse8-keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
  kong:
    image: kong/kong-gateway:3.5
    container_name: pulse8-kong
    env_file:
      - docker-compose.env
    environment:
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key
      KONG_CLUSTER_CERT: /certs/cluster.crt
    volumes:
      - ./certs:/certs
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002

networks:
  pulse8-central-bridge:
    name: pulse8-central-bridge
