version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c track_commit_timestamp=on
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  spicedb:
    container_name: "spicedb"
    image: authzed/spicedb:latest
    ports:
      - "50051:50051"
    build:
      context: ./spicedb
      args:
        - user=${POSTGRES_USER}
        - pwd=${POSTGRES_PASSWORD}
        - postgres_db=${POSTGRES_DB}
        - postgres_port=${POSTGRES_PORT}
        - postgres_host=postgres
        - spicedb_host=spicedb
        - spicedb_key=${SPICEDB_PRESHARED_KEY}
      dockerfile: Dockerfile
    volumes:
        - ./spicedb:/app
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:50051 -Xms256m -Xmx4G"
    depends_on:
      postgres:
        condition: service_healthy
  pulse8-core-access-control:
    container_name: pulse8-core-access-control
    image: pulse8-core-access-control:latest
    depends_on:
      - spicedb
    ports:
      - "3010:3010"
      - "5010:5010"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms256m -Xmx4G"
      SPICEDB_HOST: spicedb
      SPICEDB_PORT: 50051
      SPICEDB_PRESHARED_KEY: test_key
  echo-server:
    container_name: "echoserver"
    image: inanimate/echo-server:latest
    ports:
      - "3000:8080"
  kong:
    image: kong/kong-gateway:3.5
    container_name: pulse8-kong
    env_file:
      - docker-compose.env
    environment:
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key
      KONG_CLUSTER_CERT: /certs/cluster.crt
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
      KONG_LUA_PACKAGE_PATH: /opt/kong/plugins/checkpermission/?.lua;;
      KONG_PLUGINS: bundled,checkpermission
      KONG_LOG_LEVEL: debug
    volumes:
      - ./certs:/certs
      - ./config:/opt/kong
    ports:
      - 8000:8000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /local/data/db:/data/db
