# Shared properties across all profiles
p8c:
  security:
    principal-header: "X-Authenticated-User"
    roles-header: "X-Authenticated-Roles"
  route-check:
    constants:
      objectType: "route"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/p8c-core-access-control