# Development properties
server:
  port: ${ACCESS_CONTROL_SERVER_PORT}

logging:
  level:
    com:
      synpulse8:
        pulse8:
          core:
            accesscontrolsvc: info
      authzed: info
    root: error
    org:
      apache:
        kafka: error
      springframework:
        boot: info
        kafka: error
        web: warn

spring:
  security:
    csrf:
      enabled: false

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      properties:
#        acks: all
#    consumer:
#      group-id: main
#      auto-offset-reset: earliest
#      default-topic: general





