# Shared properties across all profiles
p8c:
  security:
    principal-header: "X-Authenticated-User"
  route-check:
    constants:
      objectType: "route"
      subjRefObjType: "user"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/p8c-core-access-control