# Shared properties across all profiles
p8c:
  security:
    principal-header: "X-Authenticated-User"
    roles-header: "X-Authenticated-Roles"
  route-check:
    constants:
      objectType: "route"
      subjectType: "user"

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}