# Shared properties across all profiles
p8c:
  security:
    principal-header: "X-Authenticated-User"
    roles-header: "X-Authenticated-Roles"
  route-check:
    constants:
      objectType: "route"
      subjectType: "user"

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    listener:
      missing-topics-fatal: false
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL}
    # add this config for producer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        acks: all
    # add this config for consumer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific:
          avro:
#        metadata:
#          max:
#            age:
#              ms: 300000