# Changes here will be overwritten by Copier
_commit: 344ff7d
_src_path: .
add_aquasec: true
add_core_iam_feign: true
add_database: true
add_docker: true
add_env_prod: true
add_env_qa: true
add_example: true
add_k8s: true
add_kafka: true
add_kafka_schema_registry: true
add_keycloak: true
add_liquibase: true
add_sonar: true
add_spock: true
artifact_id_raw: yourname-backend
database_dev_schema: public
database_dev_system: postgres
database_dev_url: jdbc:postgresql://localhost:5432/postgres
database_dev_username: postgres
database_prod_schema: public
database_prod_system: postgres
database_prod_url: jdbc:postgresql://localhost:5432/postgres
database_prod_username: postgres
database_qa_schema: public
database_qa_system: postgres
database_qa_url: jdbc:postgresql://localhost:5432/postgres
database_qa_username: postgres
docker_database_url: jdbc:postgresql://pulse8-central-postgres:5432/postgres
docker_image_container_group: services
docker_image_network_name: pulse8-central-bridge
docker_image_port_debug: 5010
docker_image_port_run: 3010
github_actions_workflow_name: PULSE8-CORE YOUR NAME BACKEND CI
group_id: com.synpulse8.pulse8.core
k8s_database_url: jdbc:postgresql://pulse8-central-postgres:5432/postgres
k8s_port: 3010
k8s_port_debug: 5010
k8s_replicas_count: 3
kafka_add_example: true
kafka_dev_bootstrap_servers: localhost:9092
kafka_dev_default_topic: general
kafka_dev_group_id: main
kafka_prod_bootstrap_servers: localhost:9092
kafka_prod_default_topic: general
kafka_prod_group_id: main
kafka_qa_bootstrap_servers: localhost:9092
kafka_qa_default_topic: general
kafka_qa_group_id: main
kafka_schema_registry_url: http://schemaregistry:8084
keycloak_dev_client_id: p8c-test
keycloak_dev_client_secret: ''
keycloak_dev_issuer_uri: https://keycloak.pulse8.synpulse8.com/realms/master
keycloak_dev_redirect_uri: ''
keycloak_prod_client_id: p8c-test
keycloak_prod_client_secret: ''
keycloak_prod_issuer_uri: https://keycloak.pulse8.synpulse8.com/realms/master
keycloak_prod_redirect_uri: ''
keycloak_qa_client_id: p8c-test
keycloak_qa_client_secret: ''
keycloak_qa_issuer_uri: https://keycloak.pulse8.synpulse8.com/realms/master
keycloak_qa_redirect_uri: ''
project_description: Template build full
project_id: pulse8-yourname-backend
project_name: Pulse8 YourName Backend
sonar_project_key_suffix: pulse8-core-backend-template
