apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.network/pulse8-central-bridge: "true"
        io.kompose.service: mongodb
    spec:
      containers:
        - image: mongo:7.0.5
          name: mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
      restartPolicy: Always
