apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse8-yourname-backend-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: synpulse-jfrog-docker-credential
      containers:
        - name: pulse8-yourname-backend
          image: synpulse.jfrog.io/s8-docker/synpulse-group-pulse8-yourname-backend-main:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: pulse8-yourname-backend-config
          ports:
            - containerPort: 3010
            - containerPort: 5010
