apiVersion: v1
kind: Service
metadata:
  name: pulse8-yourname-backend-service
spec:
  type: ClusterIP
  ports:
    - port: 3010
      protocol: TCP
      targetPort: 3010
  selector:
    app: pulse8-yourname-backend
