apiVersion: v1
kind: Service
metadata:
  name: pulse8-core-access-control-service
spec:
  type: ClusterIP
  ports:
    - port: 3010
      name: run
      protocol: TCP
      targetPort: 3010
    - port: 3010
      name: debug
      protocol: TCP
      targetPort: 3010
  selector:
    app: pulse8-core-access-control